server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.plist$ {
        add_header Content-Type "text/xml; charset=utf-8";
    }

    location ~* \.ipa$ {
        add_header Content-Type "application/octet-stream";
    }

    gzip on;
    gzip_types text/html text/css application/javascript;
}
